"""Adicionar dados TRT ao projeto

Revision ID: 59589d72ac04
Revises: 8465c4db4cba
Create Date: 2026-07-06 15:54:23.530558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59589d72ac04'
down_revision = '8465c4db4cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas_fiscais')
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trt_nome', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('trt_cpf_cnpj', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('trt_telefone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('trt_contato', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('trt_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('trt_endereco', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('trt_cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('trt_uf', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_column('trt_uf')
        batch_op.drop_column('trt_cidade')
        batch_op.drop_column('trt_endereco')
        batch_op.drop_column('trt_email')
        batch_op.drop_column('trt_contato')
        batch_op.drop_column('trt_telefone')
        batch_op.drop_column('trt_cpf_cnpj')
        batch_op.drop_column('trt_nome')

    op.create_table('notas_fiscais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('financeiro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('data_emissao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('faturado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('arquivo_pdf', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['financeiro_id'], ['financeiro.id'], name=op.f('notas_fiscais_financeiro_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notas_fiscais_pkey'))
    )
    # ### end Alembic commands ###
