"""Adicionar faturado_por e data_prevista_recebimento

Revision ID: 8465c4db4cba
Revises: 38f0b4681b5b
Create Date: 2026-07-06 10:16:14.584826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8465c4db4cba'
down_revision = '38f0b4681b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financeiro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faturado_por', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('data_prevista_recebimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financeiro', schema=None) as batch_op:
        batch_op.drop_column('data_prevista_recebimento')
        batch_op.drop_column('faturado_por')

    # ### end Alembic commands ###
