"""Criando tabela financeiro

Revision ID: 9936196ece1f
Revises: 
Create Date: 2026-07-03 13:18:57.416220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9936196ece1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financeiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('valor_contrato', sa.Float(), nullable=True),
    sa.Column('valor_recebido', sa.Float(), nullable=True),
    sa.Column('nota_fiscal', sa.String(length=50), nullable=True),
    sa.Column('data_faturamento', sa.Date(), nullable=True),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financeiro')
    # ### end Alembic commands ###
