"""corrige financeiro planejamento

Revision ID: abfeafffa2c1
Revises: 3c38f202080d
Create Date: 2026-07-27 12:01:09.346167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abfeafffa2c1'
down_revision = '3c38f202080d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('contato')

    with op.batch_alter_table('financeiro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planejamento_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('financeiro_projeto_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['planejamento_id'])
        batch_op.drop_constraint(batch_op.f('financeiro_projeto_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'planejamentos', ['planejamento_id'], ['id'])
        batch_op.drop_column('projeto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financeiro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projeto_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('financeiro_projeto_id_fkey'), 'projetos', ['projeto_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('financeiro_projeto_id_key'), ['projeto_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('planejamento_id')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contato', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
