"""Adiciona dados de faturamento ao financeiro

Revision ID: fc675f2c7198
Revises: 59589d72ac04
Create Date: 2026-07-06 16:07:25.624976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc675f2c7198'
down_revision = '59589d72ac04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financeiro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faturamento_nome', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('faturamento_cpf_cnpj', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('faturamento_telefone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('faturamento_contato', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('faturamento_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('faturamento_endereco', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('faturamento_cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('faturamento_uf', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financeiro', schema=None) as batch_op:
        batch_op.drop_column('faturamento_uf')
        batch_op.drop_column('faturamento_cidade')
        batch_op.drop_column('faturamento_endereco')
        batch_op.drop_column('faturamento_email')
        batch_op.drop_column('faturamento_contato')
        batch_op.drop_column('faturamento_telefone')
        batch_op.drop_column('faturamento_cpf_cnpj')
        batch_op.drop_column('faturamento_nome')

    # ### end Alembic commands ###
